<#
.SYNOPSIS
    全製品共通の Inno Setup インストーラービルドスクリプト

.DESCRIPTION
    insight-common/config/installer.ts の構成に基づいて .iss ファイルを自動生成し、
    Inno Setup でコンパイルしてインストーラー exe を出力する。

    各製品リポジトリの build.ps1 から呼び出す想定。

.PARAMETER ProductCode
    製品コード（INSS, IOSH, IOSD, INPY, INMV, INIG, INBT, INCA, IVIN）

.PARAMETER AppVersion
    アプリケーションバージョン（例: "1.0.0"）

.PARAMETER PublishDir
    dotnet publish 出力ディレクトリ（self-contained ビルド済みファイル群）

.PARAMETER OutputDir
    インストーラー exe の出力先ディレクトリ（デフォルト: "Output"）

.PARAMETER InsightCommonDir
    insight-common サブモジュールのパス（デフォルト: "insight-common"）

.PARAMETER SkipBuild
    dotnet publish をスキップするか（既にビルド済みの場合）

.EXAMPLE
    # InsightOfficeSheet のインストーラーをビルド
    .\insight-common\scripts\build-installer.ps1 `
        -ProductCode "IOSH" `
        -AppVersion "1.0.0" `
        -PublishDir "src\InsightOfficeSheet.App\bin\Release\net8.0-windows\win-x64\publish"

.EXAMPLE
    # InsightBot (Orchestrator) のインストーラーをビルド
    .\insight-common\scripts\build-installer.ps1 `
        -ProductCode "INBT" `
        -AppVersion "1.0.0" `
        -PublishDir "csharp\src\InsightBotRPA.Studio\bin\Release\net8.0-windows\win-x64\publish"
#>

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("INSS", "IOSH", "IOSD", "INPY", "INMV", "INIG", "INBT", "INCA", "IVIN")]
    [string]$ProductCode,

    [Parameter(Mandatory = $true)]
    [string]$AppVersion,

    [Parameter(Mandatory = $true)]
    [string]$PublishDir,

    [string]$OutputDir = "Output",
    [string]$InsightCommonDir = "insight-common",
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

# =============================================================================
# 設定の読み込み
# =============================================================================

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  HARMONIC insight Installer Builder" -ForegroundColor Cyan
Write-Host "  Product: $ProductCode  Version: $AppVersion" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# installer.ts の構成を JSON に出力
$configJson = Join-Path $env:TEMP "hi-installer-$ProductCode.json"
Write-Host "[1/4] Exporting installer config..." -ForegroundColor Yellow

$exportScript = Join-Path $InsightCommonDir "scripts\export-installer-config.ts"
if (-not (Test-Path $exportScript)) {
    Write-Error "export-installer-config.ts not found at: $exportScript"
    exit 1
}

npx tsx $exportScript $ProductCode $configJson
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to export installer config"
    exit 1
}

$config = Get-Content $configJson -Encoding UTF8 | ConvertFrom-Json
Write-Host "  Installer type: $($config.installerType)" -ForegroundColor Gray

# =============================================================================
# PublishDir の確認
# =============================================================================

$resolvedPublishDir = Resolve-Path $PublishDir -ErrorAction SilentlyContinue
if (-not $resolvedPublishDir) {
    Write-Error "Publish directory not found: $PublishDir"
    Write-Host "  Run 'dotnet publish -c Release -r win-x64 --self-contained' first." -ForegroundColor Red
    exit 1
}
Write-Host "  Publish dir: $resolvedPublishDir" -ForegroundColor Gray

# 出力ディレクトリ作成
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir | Out-Null
}
$resolvedOutputDir = Resolve-Path $OutputDir

# =============================================================================
# .iss ファイル生成
# =============================================================================

Write-Host "[2/4] Generating Inno Setup script..." -ForegroundColor Yellow

$issFile = Join-Path $env:TEMP "$($config.app.executable -replace '\.exe$', '')-Setup.iss"
$appName = $config.app.executable -replace '\.exe$', ''

# [Setup] セクション
$issContent = @"
; =============================================================================
; $appName Installer — Auto-generated by build-installer.ps1
; Do not edit manually. Regenerate with:
;   .\insight-common\scripts\build-installer.ps1 -ProductCode $ProductCode ...
; =============================================================================

#define AppVersion "$AppVersion"

[Setup]
AppId=$($config.innoSetup.setup.AppId)
AppName=$($config.innoSetup.setup.AppName)
AppVersion={#AppVersion}
AppVerName=$appName {#AppVersion}
AppPublisher=$($config.innoSetup.setup.AppPublisher)
AppPublisherURL=$($config.innoSetup.setup.AppPublisherURL)
AppSupportURL=$($config.innoSetup.setup.AppSupportURL)
DefaultDirName=$($config.innoSetup.setup.DefaultDirName)
DefaultGroupName=$($config.innoSetup.setup.DefaultGroupName)
OutputDir=$resolvedOutputDir
OutputBaseFilename=$($config.innoSetup.setup.OutputBaseFilename)
Compression=$($config.innoSetup.setup.Compression)
SolidCompression=$($config.innoSetup.setup.SolidCompression)
ArchitecturesInstallIn64BitMode=$($config.innoSetup.setup.ArchitecturesInstallIn64BitMode)
MinVersion=$($config.innoSetup.setup.MinVersion)
PrivilegesRequired=admin
WizardStyle=modern
SetupIconFile=
UninstallDisplayIcon={app}\$($config.app.executable)

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
"@

# デスクトップショートカット
if ($config.app.createDesktopShortcut) {
    $issContent += @"

Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
"@
}

# [Files] セクション
$issContent += @"

[Files]
Source: "$resolvedPublishDir\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
"@

# サービス + トレイアプリの追加ファイル（INBT 用）
if ($config.service) {
    $issContent += @"

; Orchestrator サービスとトレイアプリは同じ publish ディレクトリに含まれている想定
; 個別にビルドする場合は Source パスを調整してください
"@
}

# [Icons] セクション
$issContent += @"

[Icons]
Name: "{group}\$appName"; Filename: "{app}\$($config.app.executable)"
Name: "{group}\{cm:UninstallProgram,$appName}"; Filename: "{uninstallexe}"
"@

if ($config.app.createDesktopShortcut) {
    $issContent += "`r`nName: `"{commondesktop}\$appName`"; Filename: `"{app}\$($config.app.executable)`"; Tasks: desktopicon"
}

# トレイアプリのスタートアップ登録
if ($config.trayApp) {
    $issContent += @"
Name: "{commonstartup}\$($config.trayApp.windowTitle)"; Filename: "{app}\$($config.trayApp.executable)"
"@
}

# [Registry] セクション
if ($config.innoSetup.registry.Count -gt 0) {
    $issContent += "`r`n`r`n[Registry]`r`n"
    foreach ($entry in $config.innoSetup.registry) {
        $issContent += "$entry`n"
    }
}

# [Run] セクション（インストール後実行）
$issContent += @"

[Run]
"@

# サービス登録（INBT）
if ($config.service) {
    $svcName = $config.service.serviceName
    $svcExe = $config.service.executable
    $svcDesc = $config.service.descriptionJa

    $issContent += @"
; Windows サービス登録
Filename: "sc"; Parameters: "create $svcName binPath= ""{app}\$svcExe"" start= auto obj= ""NT AUTHORITY\LocalService"" DisplayName= ""$($config.service.displayName)"""; Flags: runhidden waituntilterminated; StatusMsg: "サービスを登録しています..."
Filename: "sc"; Parameters: "description $svcName ""$svcDesc"""; Flags: runhidden waituntilterminated
Filename: "sc"; Parameters: "failure $svcName reset= 86400 actions= restart/10000/restart/10000/restart/10000"; Flags: runhidden waituntilterminated
"@
}

# ファイアウォール（INBT）
foreach ($rule in $config.firewallRules) {
    $profiles = ($rule.profiles -join ",")
    $issContent += @"
; ファイアウォールルール
Filename: "netsh"; Parameters: "advfirewall firewall add rule name=""$($rule.name)"" dir=$($rule.direction) action=allow protocol=$($rule.protocol) localport=$($rule.port) profile=$profiles"; Flags: runhidden waituntilterminated; StatusMsg: "ファイアウォールを設定しています..."
"@
}

# サービス起動（INBT）
if ($config.service) {
    $issContent += @"
; サービス起動
Filename: "sc"; Parameters: "start $($config.service.serviceName)"; Flags: runhidden waituntilterminated; StatusMsg: "サービスを起動しています..."
"@
}

# アプリ起動
$issContent += "`r`nFilename: `"{app}\$($config.app.executable)`"; Description: `"Launch $appName`"; Flags: nowait postinstall skipifsilent"

# [UninstallRun] セクション
$issContent += @"

[UninstallRun]
"@

if ($config.service) {
    $issContent += @"
; サービス停止・削除
Filename: "sc"; Parameters: "stop $($config.service.serviceName)"; Flags: runhidden; RunOnceId: "StopService"
Filename: "sc"; Parameters: "delete $($config.service.serviceName)"; Flags: runhidden; RunOnceId: "DeleteService"
"@
}

foreach ($rule in $config.firewallRules) {
    $issContent += @"
; ファイアウォールルール削除
Filename: "netsh"; Parameters: "advfirewall firewall delete rule name=""$($rule.name)"""; Flags: runhidden; RunOnceId: "RemoveFirewall"
"@
}

# [UninstallDelete] セクション
$issContent += @"

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\HarmonicInsight\$appName"
Type: filesandordirs; Name: "{userappdata}\HarmonicInsight\$appName"
"@

# セクション間に空行を保証
$issContent = $issContent -replace '(?<!\r?\n\r?\n)(\r?\n)(\[(Files|Icons|Registry|Run|UninstallRun|UninstallDelete)\])', "`r`n`r`n`$2"

# .iss ファイルに書き出し（BOM なし UTF-8）
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($issFile, $issContent, $utf8NoBom)
Write-Host "  Generated: $issFile" -ForegroundColor Gray

# =============================================================================
# Inno Setup コンパイル
# =============================================================================

Write-Host "[3/4] Compiling installer with Inno Setup..." -ForegroundColor Yellow

# Inno Setup のパスを検索
$innoSetupPaths = @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles}\Inno Setup 6\ISCC.exe",
    "${env:LOCALAPPDATA}\Programs\Inno Setup 6\ISCC.exe"
)

$iscc = $null
foreach ($p in $innoSetupPaths) {
    if (Test-Path $p) {
        $iscc = $p
        break
    }
}

if (-not $iscc) {
    Write-Error @"
Inno Setup 6 not found. Install from:
  https://jrsoftware.org/isdl.php

Or install via winget:
  winget install JRSoftware.InnoSetup
"@
    exit 1
}

Write-Host "  Inno Setup: $iscc" -ForegroundColor Gray

& $iscc $issFile
if ($LASTEXITCODE -ne 0) {
    Write-Error "Inno Setup compilation failed"
    exit 1
}

# =============================================================================
# 完了
# =============================================================================

Write-Host ""
Write-Host "[4/4] Build complete!" -ForegroundColor Green

$installerExe = Get-ChildItem -Path $resolvedOutputDir -Filter "*Setup*.exe" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
if ($installerExe) {
    $sizeMB = [math]::Round($installerExe.Length / 1MB, 1)
    Write-Host ""
    Write-Host "  Installer: $($installerExe.FullName)" -ForegroundColor White
    Write-Host "  Size:      $sizeMB MB" -ForegroundColor White
    Write-Host "  Product:   $ProductCode ($appName)" -ForegroundColor White
    Write-Host "  Version:   $AppVersion" -ForegroundColor White
    Write-Host "  Type:      $($config.installerType)" -ForegroundColor White
    if ($config.service) {
        Write-Host "  Service:   $($config.service.serviceName) (port $($config.firewallRules[0].port))" -ForegroundColor White
    }
}

# テンポラリファイル削除
Remove-Item $configJson -ErrorAction SilentlyContinue
Remove-Item $issFile -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Done." -ForegroundColor Cyan
