# ============================================================
# XcodeGen プロジェクト定義
#
# 使い方:
#   make setup          # XcodeGen インストール + プロジェクト生成
#   make open           # Xcode で開く
#   make bump-patch     # バージョン +1
#
# .xcodeproj は gitignore されるため、コミットしない。
# → .pbxproj マージコンフリクト地獄を完全回避。
#
# ビルド設定は Configuration/*.xcconfig で管理。
# → Xcode GUI で設定を変更しても xcconfig が優先される。
#
# __AppName__ を実際のアプリ名 (PascalCase) に置換してください。
# __APPNAME__ を実際のターゲット名 (小文字) に置換してください。
# __APP_BUNDLE_ID__ を Bundle Identifier に置換してください。
# ============================================================

name: __AppName__

options:
  bundleIdPrefix: com.harmonic.insight
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: ja
  xcodeVersion: "16.2"
  generateEmptyDirectories: true
  # .xcodeproj 内のビルド設定を最小化（xcconfig に委譲）
  minimumXcodeGenVersion: "2.38.0"

# xcconfig でビルド設定を一元管理
configFiles:
  Debug: Configuration/Debug.xcconfig
  Release: Configuration/Release.xcconfig

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""

targets:
  __AppName__:
    type: application
    platform: iOS
    sources:
      - path: __APPNAME__
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: __APP_BUNDLE_ID__
        INFOPLIST_FILE: __APPNAME__/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTED_INTERFACE_ORIENTATIONS: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SUPPORTED_INTERFACE_ORIENTATIONS~ipad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    configFiles:
      Debug: Configuration/Debug.xcconfig
      Release: Configuration/Release.xcconfig
    # SPM 依存を追加する場合:
    # dependencies:
    #   - package: KeychainAccess
    #     product: KeychainAccess

# SPM パッケージを追加する場合:
# packages:
#   KeychainAccess:
#     url: https://github.com/kishikawakatsumi/KeychainAccess.git
#     from: "4.2.2"
